import org.junit.runner.JUnitCore;
import org.junit.runner.Result;
import org.junit.runner.notification.Failure;


/*************************************
**      RUNNER DEPENDENCIES         **
**************************************
*
*	Must compile the JunitTestSuite.java
*  file first to create the needed
*  JunitTestSuite.class
*
*  --- DO NOT EDIT THIS FILE ---
*
*/

public class TestSuiteRunner {
   public static void main(String[] args) {
      Result result = JUnitCore.runClasses(JunitTestSuite.class);
      for (Failure failure : result.getFailures()) {
         System.out.println(failure.toString());
      }
      System.out.println("All Tests Passed: " + result.wasSuccessful());
   }
} 